### PR TITLE
Navigation links

### PR DESCRIPTION
**Pull request by eugenijusr**
- [x] Add pagination links
- [x] Change the way default serializer is selected - do not use the controller name for that
- [x] Remove ActiveModelSerializers adapter

### CODE REVIEW

**Comment by eugenijusr** [comment]
@deviantbits Can you take a look at this PR and see if this can be merged into the main?

**Comment by deviantbits** [comment]
@eugenijusr Sure, I'll take a look!

**Comment by eugenijusr** [comment]
I removed the ActiveModelSerializers adapter because first of all it depends on an unlisted dependency and secondly it's not compatible with the latest RC3 version of the gem. We have to wait until the API stabilizes a bit and then release an adapter that would attach links to the JSON.

**Comment by deviantbits** [comment]
But how does this affect the output? How do you make it work without an adapter?

**Comment by eugenijusr** [comment]
The links are just not rendered for now with this.

**Comment by deviantbits** [comment]
@eugenijusr Could you test this again? If it's fine, let's merge it and release `v0.5.0`.

**Pull request merged**
